# Generated by Django 5.2.8 on 2025-12-13 22:47

import django.core.validators
import django.db.models.deletion
import watchlist_app.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Watchlist', validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(15), watchlist_app.validators.validate_name])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(8)])),
                ('cash', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('equity_final', models.DecimalField(decimal_places=2, max_digits=14)),
                ('return_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('buy_hold_return_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cagr_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('calmar_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('alpha_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('max_drawdown_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='watchlist_app.watchlist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_watchlist_per_user'),
        ),
        migrations.AddConstraint(
            model_name='watchlistitem',
            constraint=models.UniqueConstraint(fields=('watchlist', 'ticker'), name='unique_ticker_per_watchlist'),
        ),
    ]
