# Generated by Django 5.2.8 on 2025-12-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='return_ann_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
